#!/bin/sh /etc/rc.common
# CS 326 sign-in portal
START=95
STOP=10
USE_PROCD=1
PROG=/usr/sbin/classnet-portal

start_service() {
	[ -x "$PROG" ] || return 1
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param file /etc/classnet/portal.conf
	procd_close_instance
}
